[package]
name = "penrose_config"
version = "0.1.0"
authors = ["Michael Cooney <MC509119@ohio.edu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
penrose = "0.2"
simplelog = "0.8"
